### ISSUE TITLE
Display values from multiple contracts in one component

### ISSUE THREAD

**Issue by timjlowe** [Horyus/vortex-components#2]
Hey,
Great work with Vortex.  I had a quick question.... If I wanted to display values from multiple contracts in one React Component, should I use one of the Vortex Components or write my own.  For example I want to display the result of totalSupply and balanceOf  calls from three different ERC20 tokens in one component?
Thanks!

**Comment by mortimr** [comment]
Hi @timjlowe,

unfortunately there is no component inside this module that does what you are trying to do. You will have to create it yourself !

Be sure to check the code of the already existing components. I'll guide you, let's say you want a component that takes as prop an array with 3 ERC20 addresses and a user address. It will look a bit like this (assuming that your contracts are already loaded inside the store).

```jsx
import {connect} from 'vort_x-components';
import React from 'react';

class _Balances extends React.Component {
    render() {
                    return (<div>
                    <p>{this.props.balance_one || 'Loading ...'}</p>
                    <p>{this.props.balance_two || 'Loading ...'}</p>
                    <p>{this.props.balance_three || 'Loading ...'}</p>
                </div>);
    }
}

onst mapStateToProps = (state, ownProps) => {
    return {
        ...ownProps, // very important if you want to keep the props you initially gave
        balance_one: state.contracts.ERC20[ownProps.ERC20[0]].instance.vortex.balanceOf.vortexData({}, ownProps.account), // I will change this soon to have transaction arguments as last argument
        balance_two: state.contracts.ERC20[ownProps.ERC20[1]].instance.vortex.balanceOf.vortexData({}, ownProps.account),
        balance_three: state.contracts.ERC20[ownProps.ERC20[2]].instance.vortex.balanceOf.vortexData({}, ownProps.account),
    }
};

export const Balances = connect(_Balance, mapStateToProps);
```

and you would use it like this

```jsx
<Balances ERC20={['0x...', '0x...', '0x...']} account="0x..." />
```

(I am working on better tutorials for basic actions like loading a contract, calling constant methods, calling state modifying methods etc ...)

**Comment by timjlowe** [comment]
Ok, that looks very straightforward!

I have also been struggling to retrieve (truffle) deployed contract addresses from the store.  So if I was using vortex gate to load the erc20 abi's, how would I then reference them so as not to hard code the addresses.

(Sorry for the basic questions!)

**Comment by mortimr** [comment]
Well it all depends on how you recover the address of the contracts, but you could give it dynamically to the component I showed you before. 

Also you can load a new smart contract by calling `Vortex.get().loadContract("name", "address")` (recover `Vortex` from `vort_x`) module.

Combining the two you can dynamically load contract addresses given as props !

```jsx
import {connect} from 'vort_x-components';
import React from 'react';
import {Vortex} from 'vort_x';

class _Balances extends React.Component {
    constructor(props) {
        super(props);
        this.props.ERC20[0] = this.props.ERC20[0].toLowerCase()
        this.props.ERC20[1] = this.props.ERC20[1].toLowerCase()
        this.props.ERC20[2] = this.props.ERC20[2].toLowerCase()
        if (!state.contracts.ERC20[this.props.ERC20[0]])
            Vortex.get().loadContract("ERC20", this.props.ERC20[0]);
        if (!state.contracts.ERC20[this.props.ERC20[1]])
            Vortex.get().loadContract("ERC20", this.props.ERC20[1]);
        if (!state.contracts.ERC20[this.props.ERC20[2]])
            Vortex.get().loadContract("ERC20", this.props.ERC20[2]);
    }

    render() {
                    return (<div>
                    <p>{this.props.balance_one || 'Loading ...'}</p>
                    <p>{this.props.balance_two || 'Loading ...'}</p>
                    <p>{this.props.balance_three || 'Loading ...'}</p>
                </div>);
    }
}
const mapStateToProps = (state, ownProps) => {
    return {
        ...ownProps, // very important if you want to keep the props you initially gave
        balance_one: state.contracts.ERC20[ownProps.ERC20[0]] ? state.contracts.ERC20[ownProps.ERC20[0]].instance.vortex.balanceOf.vortexData({}, ownProps.account) : undefined, // I will change this soon to have transaction arguments as last argument
        balance_two: state.contracts.ERC20[ownProps.ERC20[1]] ? state.contracts.ERC20[ownProps.ERC20[1]].instance.vortex.balanceOf.vortexData({}, ownProps.account) : undefined,
        balance_three: state.contracts.ERC20[ownProps.ERC20[2]] ? state.contracts.ERC20[ownProps.ERC20[2]].instance.vortex.balanceOf.vortexData({}, ownProps.account) : undefined,
    }
};

export const Balances = connect(_Balance, mapStateToProps);
```

Now any contract you give will get loaded inside the store before. Anyway, if you want to recover the addresses of the contracts already deployed, you can use `Vortex` to directly access the state.

```js
Object.keys(Vortex.get().State.contracts.ERC20).filter(elem => elem !== 'artifact');
```

It will give you an array of loaded addresses (without the 'artifact')

Also beware, address are always to lowercase (in JS, call `.toLowerCase()` on any string) inside Vortex. This is the best compromise I found for everyone to be able to access their contracts no matter if the address given is lowercase, uppercase, checksummed ...

**Comment by mortimr** [comment]
You are right ! 

(Also you should look at the code in TS inside the `_sources` directory instead of the transpiled code :) )

Thanks for reporting it, it will be fixed in next version !

**Comment by timjlowe** [comment]
What triggers the loading of the contract address in to the store?  When I look at the contract in the store, it only has the ABI and not the deployed address?  (This is from within a component loaded in the VortexWeb3Loaded of VortexGate).

**Comment by mortimr** [comment]
Contract loading works this way:

- Vortex store is initialized and given contracts informations (abi)

https://github.com/Horyus/vortex/blob/7e8140507a5dfd924520d7e555e5e10199a63a59/_sources/sources/vortex.ts#L56-L60

- Vortex instance exposes a loadContract method that triggers a `CONTRACT_LOAD` action in redux (with name of contract + address of contract)

https://github.com/Horyus/vortex/blob/7e8140507a5dfd924520d7e555e5e10199a63a59/_sources/sources/vortex.ts#L148-L154


- Redux saga responds to action dispatch and asynchronously loads the desired contract (dispatches `CONTRACT_LOADED` or `CONTRACT_ERROR` and a `FEED_NEW_CONTRACT` if it succeded)

https://github.com/Horyus/vortex/blob/7e8140507a5dfd924520d7e555e5e10199a63a59/_sources/sources/contracts/contracts.saga.ts#L321

Can you explain me where you are looking on the store ?

**Comment by timjlowe** [comment]
Basically whenever I try and access the deployed contracts in the store from a component.  I have tried starting a new basic app and tried using the balance component you described above and get the same problem.  
```
import React, { Component } from 'react'
import {VortexGate, VortexWeb3Loaded, VortexWeb3LoadError, VortexWeb3NetworkError, VortexWeb3Loading, VortexWeb3Locked, VortexMetamaskLoader} from "vort_x-components";
import MyToken from '../build/contracts/MyToken.json'
import Web3 from 'web3';
import {FeedNotifications} from "./demo-sections/feed-notifications";
import {Balances} from "./demo-sections/balances";

class App extends Component {
    render() {
        return (
            <VortexGate contracts={{
                type: 'truffle',
                truffle_contracts: [MyToken],
                preloaded_contracts: ["MyToken"]
            }} network_contracts={[MyToken]} loader={VortexMetamaskLoader(Web3)}>
                <VortexWeb3Loaded>
                    <FeedNotifications>
                        <div className="App">
                            <main className="container">
                                <div className="pure-g">
                                    <div className="pure-u-1-1">
                                        VortΞx Demo Loaded !
                                    </div>
                                    <div>
                                        <Balances MyToken='0x0d0020758c4f1f85b2b89322ff01a67ce30fb0f8' account='0xe87529a6123a74320e13a6dabf3606630683c029' />
                                    </div>
                                </div>         
                            </main>
                        </div>
                    </FeedNotifications>
                </VortexWeb3Loaded>
.......
```
Balances.js:
```
import {connect} from 'vort_x-components';
import React from 'react';

class _Balances extends React.Component {
    render() {
                return (<div>
                    <p>{this.props.balance_one || 'Loading ...'}</p>
                </div>);
    }
}

const mapStateToProps = (state, ownProps) => {
    return {
        ...ownProps, 
        balance_one: state.contracts.MyToken[ownProps.MyToken[0]].instance.vortex.balanceOf.vortexData({}, ownProps.account), 
    }
};

export const Balances = connect(_Balances, mapStateToProps);
```
This gives the error:
'uncaught at callResolveWeb3 TypeError: Cannot read property 'instance' of undefined
    at Function.mapStateToProps [as mapToProps] (http://localhost:3000/static/js/bundle.js:210250:68)'

If I inspect the state.contracts object I see:
```
state.contracts.MyToken
{artifact: {…}}
artifact
:
{abi: Array(25), bytecode: "0x6080604052600436106100fc576000357c01000000000000…4f10cf9e7e20d5a92fc3fdaa7a3afe8f718788e3201f40029", name: "MyToken"}
__proto__
:
Object
```
What am I missing?

**Comment by mortimr** [comment]
Ok I have some questions:
- Have you deployed your Token contract on the network you are connected ? What is the content of `MyToken.networks` ? When you run the Dapp, what is the content inside `state.web3` ?
- If you haven't deployed it and expect to load a new instance for `0x0d0020758c4f1f85b2b89322ff01a67ce30fb0f8`, then you should look at my one of my previous answers, where I show you how to actually load the contract inside the `Balances` component `constructor`.

What is happening is that Vortex is not getting any instruction to load your contract, but you're still accessing `instance` in the `mapStateToProps` of `Balances`. 
Look at the last version of `Balances` I gave you as answer and look at how I check if the instance has been loaded before trying to call the method.

**Comment by timjlowe** [comment]
It is deployed:
```
 MyToken.networks
{ '1528961970961':
   { events: {},
     links: {},
     address: '0x0d0020758c4f1f85b2b89322ff01a67ce30fb0f8',
     transactionHash: '0x20157e7c3ca714d37a3f25d5c635ae93383ce3472764b0c72233ca9b12ae8402' } }
```
web3:
```
{status: "LOADED", network_id: 1528961970961, _: Web3, coinbase: "0x3cb12c8a63376f7c3b1673e81854aeceea3998e2"}coinbase: "0x3cb12c8a63376f7c3b1673e81854aeceea3998e2"network_id: 1528961970961status: "LOADED"_: Web3 {_requestManager: RequestManager, givenProvider: MetamaskInpageProvider, providers: {…}, _provider: MetamaskInpageProvider, …}__proto__: Object
```

That works, though it seems initially when the contract is loaded, the instance property is not available:
ncaught at onLoadContractInitialize TypeError: Cannot read property 'vortex' of undefined

I had to set this.state = to store.getState() as I was getting a store not recognized error.  My code now looks like this:
```import {connect} from 'vort_x-components';
import React from 'react';
import {Vortex} from 'vort_x';

class _Balances extends React.Component {

        constructor(props) {
        super(props);

        this.props.MyToken[0] = this.props.MyToken[0].toLowerCase()
        this.state = this.props.store.getState();
        if (!this.state.contracts.MyToken[this.props.MyToken[0]])
            Vortex.get().loadContract("MyToken", this.props.MyToken[0]);

    }

    render() {
                return (<div>
                    <p>{this.props.balance_one || 'Loading ...'}</p>
                </div>);
    }
}

const mapStateToProps = (state, ownProps) => {
    return {
        ...ownProps, 
        balance_one: state.contracts.MyToken[ownProps.MyToken[0]] ? state.contracts.MyToken[ownProps.MyToken[0]].instance.vortex.balanceOf.vortexData({}, ownProps.account) : undefined,
    }
};

export const Balances = connect(_Balances, mapStateToProps);
```

**Comment by mortimr** [comment]
Oh I did a mistake on the example before !

This should work:
```jsx
import {connect} from 'vort_x-components';
import React from 'react';
import {Vortex} from 'vort_x';

class _Balances extends React.Component {
    constructor(props) {
        super(props);
        this.props.ERC20[0] = this.props.ERC20[0].toLowerCase()
        if (!this.props.store.getState().contracts.ERC20[this.props.ERC20[0]])
            Vortex.get().loadContract("ERC20", this.props.ERC20[0]);
    }

    render() {
                    return (<div>
                    <p>{this.props.balance || 'Loading ...'}</p>
                </div>);
    }
}
const mapStateToProps = (state, ownProps) => {
    return {
        ...ownProps, // very important if you want to keep the props you initially gave
        balance: state.contracts.ERC20[ownProps.ERC20[0]] ? state.contracts.ERC20[ownProps.ERC20[0]].instance.vortex.balanceOf.vortexData({}, ownProps.account) : undefined, // I will change this soon to have transaction arguments as last argument
    }
};

export const Balances = connect(_Balances, mapStateToProps);
```

I don't understand why you would assign the redux store state to your component state.
Do you have a repository so I can give you better advices and see what problems you are having ?

**Comment by timjlowe** [comment]
That would be great.  I'll upload it tonight and send you a link.
